name: paysenta
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  gap: ^2.0.0
  dio: ^4.0.6
  iconly: ^1.0.1
  feather_icons: ^1.2.0
  flutter_svg: ^1.1.2
  path: ^1.8.1
  path_provider: ^2.0.11
  flutter_riverpod: ^1.0.4
  intl: ^0.17.0
  google_fonts: ^5.1.0
#  url_launcher: ^6.1.5
  hive: ^2.2.3
  shared_preferences: ^2.0.15
#  equatable: ^2.0.3
#  json_annotation: ^4.6.0
#  freezed_annotation: ^2.1.0
  iconsax: ^0.0.8
  accordion: ^2.5.0
  country_picker:
  flutter_staggered_animations: ^1.0.0
  modal_bottom_sheet:
     git:
       url: https://github.com/followthemoney1/modal_bottom_sheet.git
       ref: main
       path: modal_bottom_sheet
  image_picker: ^0.8.5+3
#  sqflite: ^2.0.3
  pandabar: ^0.1.2
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  test: ^1.21.1
#  build_runner: ^2.2.0
#  freezed: ^2.1.0+1
#  json_serializable: ^6.3.1

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/illustrations/
#    - assets/images/onboarding/
#    - assets/images/home/
#    - assets/images/subjects/
#    - assets/icons/
#    - assets/images/lessons/
#    - assets/images/profile/
    - assets/flags/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
